/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    According: typeof import('./components/According.vue')['default']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    Article: typeof import('./components/Article.vue')['default']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATree: typeof import('ant-design-vue/es')['Tree']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    CommonPagination: typeof import('./components/CommonPagination.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconConvert: typeof import('./components/icons/IconConvert.vue')['default']
    IconDelete: typeof import('./components/icons/IconDelete.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    IconWarning: typeof import('./components/icons/IconWarning.vue')['default']
    MouseFollow: typeof import('./components/MouseFollow.vue')['default']
    PageStatus: typeof import('./components/PageStatus.vue')['default']
    PdfEmbed: typeof import('./components/PdfEmbed/src/PdfEmbed.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VDrag: typeof import('./components/VDrag.vue')['default']
    VuePdfEmbed: typeof import('./components/vue-pdf-embed/src/vue-pdf-embed.vue')['default']
  }
}
